services:
  # A web service for the FastAPI backend
  - type: web
    name: careescapes-api
    runtime: python
    plan: free
    buildCommand: ls -la && pip install -r api/requirements.txt
    startCommand: python -m uvicorn render_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_CONNECTION_STRING
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: RENDER
        value: "true"
    autoDeploy: true 